### PR TITLE
Add CNS solver following GeoStats.jl API

### PR DESCRIPTION
**Pull request by juliohm**
This PR introduces a simulation solver from GeoStats.jl so that you can assess the API. We can decide where is the best place for it. If it is not welcome here in this package, we can create a separate package where the new dependencies Meshes.jl and GeoStatsBase.jl are introduced.

Notice that right now whenever users construct samplers from CoherenetNoise.jl, they are deterministic, which is counter-intuitive. I still think that CoherentNoise.jl should consider not fixing the seed at construction time, and instead use full RNGs. That way multiple calls to sample(sampler, ...) would always produce different images. Right now I am asking for 3 realizations of the image, but they are all equal. I would need to instantiate a different sampler every time to generate a different random image.

```julia
using GeoStats
using CoherentNoise

# plot recipes
using GeoStatsPlots

# ask for simulation over a CartesianGrid or any mesh with GridTopology
problem = SimulationProblem(CartesianGrid(100,100), :z => Float64, 3)

# instantiate the solver and specify that the variable z is Perlin noise
# notice that right now the dimension is fixed, ideally I would just say
# perlin and inside the function would determine the appropriate dimension
# based on the domain from Meshes.jl
solver  = CNS(:z => (sampler=perlin_2d(),))

# generate 3 random images (which currently are equal)
ensemble = solve(problem, solver)

plot(ensemble)
```
image

### CODE REVIEW

**Comment by mfiano** [comment]
As per #7, I won't allow passing a custom RNG to a "sampler" (awful name which will change in a future API), but I did add support for defaulting to a random seed if one is not supplied. This should help one of your requests for your use case.

**Comment by mfiano** [comment]
Secondly, I do not want to depend on libraries not essential to the CoherentNoise.jl algorithms. The solver should be a secondary package for modularity and maintenance reasons.

**Comment by juliohm** [comment]
Thank you @mfiano for the prompt reply. I will close the PR and will migrate the code to some other package as you suggested.

Appreciate if you can teach me how to generate multiple random images over a general `Meshes.CartesianGrid` using the samplers in CoherentNoise.jl. What I am interested in is a simple function that loops over the centroids of the grid and simulates each pixel/voxel coherently. At the end, this function will be called multiple times to generate different images.

You can take a look at TuringPatterns.jl, which is another GeoStats.jl solver that started as a separate package and that now is maintained under our organization: https://github.com/JuliaEarth/TuringPatterns.jl

**Comment by mfiano** [comment]
The answer is quite simple: The seed needs to change between images. There needs to be some explicit point at which the seed is changed.If you change it between sampling pixels of a single image, you just *incoherent* noise images (bad). And a single sample (coord) can't know which pair of samples belong to a different "image". For some uses, there is never a different image, like if you are generating and not storing heights for a terrain, you need to get the same values back for a particular coord every time, in case you leave the area and then come back (in a game).

The solution seems to be to just use a closure that calls `perlin_Nd()` (with no seed supplied). Then everytime you call your closure you will construct a new sampler that can be used to create a different image. So you would just need to change: `:z => (sampler=perlin_2d()` to something that doesn't eagerly evaluate `perlin_2d()`, and does it only as needed, in order to get a differently seeded sampler.

**Pull request closed without merging**
